import assert from 'node:assert/strict';
import test from 'node:test';
import { hmacSha256, sha256, toHex, utf8 } from '../src/wire/sha256.ts';
import {
  answerFleetChallenge, decodeBase32, FleetKeyError, fleetDeviceToken, fleetKeyId,
  fleetProof, normalizeFleetKey,
} from '../src/wire/fleet.ts';

// ---- the primitives ------------------------------------------------------
// A hand-rolled hash is only worth having if it is pinned to the standard's own
// vectors. crypto.subtle is unavailable at http://<ip>, so this is the code
// path every browser client actually takes.

test('SHA-256 matches FIPS 180-4', () => {
  assert.equal(toHex(sha256(utf8(''))),
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');
  assert.equal(toHex(sha256(utf8('abc'))),
    'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
  assert.equal(toHex(sha256(utf8('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq'))),
    '248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1');
  // Crosses the 55-byte padding boundary, where a block gets appended.
  assert.equal(toHex(sha256(utf8('a'.repeat(1000000).slice(0, 1000)))),
    toHex(sha256(utf8('a'.repeat(1000)))));
});

test('HMAC-SHA256 matches RFC 4231', () => {
  const key1 = new Uint8Array(20).fill(0x0b);
  assert.equal(toHex(hmacSha256(key1, utf8('Hi There'))),
    'b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7');
  assert.equal(toHex(hmacSha256(utf8('Jefe'), utf8('what do ya want for nothing?'))),
    '5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843');
  // Key longer than the 64-byte block, so it is hashed first.
  const long = new Uint8Array(131).fill(0xaa);
  assert.equal(toHex(hmacSha256(long, utf8('Test Using Larger Than Block-Size Key - Hash Key First'))),
    '60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54');
});

// ---- agreement with the daemon ------------------------------------------
// Generated by internal/fleet on 2026-07-26 and pasted verbatim. If this file
// and fleet.go ever disagree, a phone or a browser silently fails to enrol with
// "that key does not belong to this fleet" and the key looks broken.

const GO_VECTORS = [
  {
    key: 'wf-byntydr27z7j3zsdpih3uulqhi',
    serverNonce: '0011223344556677',
    clientNonce: 'aabbccddeeff0011',
    machineId: 'm-cd95232395aa46ca42941bc803869022',
    keyId: '51543a8e0bc0940f',
    proof: '473b7d7041c4a7ea88545c6e0ffdc7947f56ab1efdb9cedf771ae9aedefbe0d9',
    token: '82440ec75bc794b284338694fc1469e45730e7e06b2ee411670c6382e9bf76fc',
  },
  {
    // Empty nonces and machine id: proves the trailing NUL after the LAST field
    // is really there. Drop it and this vector is the one that breaks.
    key: 'wf-aaaaaaaaaaaaaaaaaaaaaaaaaa',
    serverNonce: '',
    clientNonce: '',
    machineId: '',
    keyId: '4d2b79d8dcb608f7',
    proof: '76c3172fa64dbc28129a5bcb3fb9ae9af1e4afd3937a58e774f12e4a7192fcd8',
    token: '7cad6811ba59429dc1177c52d4a2a25aa17b31bca38c338c3cff850284b69e78',
  },
  {
    key: 'wf-dxav2wvjok3kj6hmir7ymwdj5y',
    serverNonce: 'deadbeef',
    clientNonce: 'cafebabe',
    machineId: 'm-22746fd8abb9f3e96d6a556763748c51',
    keyId: 'e7a5787208066cf5',
    proof: '0cc5448b3e5d5701467f6e7b81fa3c4bcdb70da9f57ba9cc1af11935cf37a0b8',
    token: 'aa4c85143932bc9867a5d433bca6718fd01ba6ded4ed1899f90f04673ccb689f',
  },
];

test('the proof and the token agree with the Go daemon byte for byte', () => {
  for (const v of GO_VECTORS) {
    assert.equal(fleetProof(v.key, v.serverNonce, v.clientNonce, v.machineId), v.proof, v.key);
    assert.equal(fleetDeviceToken(v.key, v.serverNonce, v.clientNonce, v.machineId), v.token, v.key);
  }
  // A proof must never be usable as a token, or a listener who captured one
  // would hold the other.
  const v = GO_VECTORS[0];
  assert.notEqual(v.proof, v.token);
});

test('the proof is bound to the machine and to both nonces', () => {
  const v = GO_VECTORS[0];
  assert.notEqual(fleetProof(v.key, v.serverNonce, v.clientNonce, 'm-somewhere-else'), v.proof);
  assert.notEqual(fleetProof(v.key, 'other', v.clientNonce, v.machineId), v.proof);
  assert.notEqual(fleetProof(v.key, v.serverNonce, 'other', v.machineId), v.proof);
});

// ---- what a human types --------------------------------------------------

test('a key survives being read off one screen and typed into another', () => {
  const canonical = 'wf-byntydr27z7j3zsdpih3uulqhi';
  for (const typed of [
    'WF-BYNTYDR27Z7J3ZSDPIH3UULQHI',
    '  wf-byntydr27z7j3zsdpih3uulqhi  ',
    'wf byntydr2 7z7j3zsd pih3uulqhi',
    'byntydr27z7j3zsdpih3uulqhi',
    'wf_byntydr27z7j3zsdpih3uulqhi',
  ]) {
    assert.equal(normalizeFleetKey(typed), canonical, typed);
    assert.equal(fleetProof(typed, 'a', 'b', 'c'), fleetProof(canonical, 'a', 'b', 'c'), typed);
  }
});

test('base32 is decoded unpadded, the way Go writes it', () => {
  // 26 chars → 16 bytes, no '=' anywhere. A decoder that demands padding throws
  // here, which is exactly the bug this pins.
  assert.equal(decodeBase32('byntydr27z7j3zsdpih3uulqhi').length, 16);
  assert.equal(toHex(decodeBase32('AAAAAAAAAAAAAAAAAAAAAAAAAA')), '00'.repeat(16));
  assert.deepEqual(Array.from(decodeBase32('AEBAGBA')), [1, 2, 3, 4]);
});

test('garbage is refused as a key rather than hashed into a wrong proof', () => {
  for (const bad of ['', '   ', 'wf-', 'hello world', 'wf-1111111111111111111111111', 'wf-short']) {
    assert.throws(() => normalizeFleetKey(bad), FleetKeyError, bad);
  }
});

// ---- the challenge answer ------------------------------------------------

test('answering a challenge produces a proof and a token the client keeps to itself', () => {
  const fixedRandom = (n: number) => new Uint8Array(n).fill(0xab);
  const answer = answerFleetChallenge('wf-byntydr27z7j3zsdpih3uulqhi', {
    enabled: true, machineId: 'm-1', serverNonce: 'sn-1',
  }, fixedRandom);
  assert.equal(answer.clientNonce, 'ab'.repeat(16));
  assert.equal(answer.proof, fleetProof('wf-byntydr27z7j3zsdpih3uulqhi', 'sn-1', answer.clientNonce, 'm-1'));
  assert.equal(answer.deviceToken, fleetDeviceToken('wf-byntydr27z7j3zsdpih3uulqhi', 'sn-1', answer.clientNonce, 'm-1'));
  // What goes on the wire is the proof; the token is derived, never sent.
  assert.notEqual(answer.proof, answer.deviceToken);
});

test('a machine with no fleet key is a different failure from a wrong key', () => {
  assert.throws(
    () => answerFleetChallenge('wf-byntydr27z7j3zsdpih3uulqhi', { enabled: false, machineId: 'm-1' }),
    /no fleet key/,
  );
  assert.throws(
    () => answerFleetChallenge('wf-byntydr27z7j3zsdpih3uulqhi', { enabled: true, machineId: 'm-1' }),
    /missing its nonce/,
  );
});

test('a fleet id identifies a key without revealing it', () => {
  const key = 'wf-dxav2wvjok3kj6hmir7ymwdj5y';
  const id = fleetKeyId(key);
  assert.equal(id.length, 16);
  assert.equal(id, fleetKeyId('  WF-DXAV2WVJ OK3KJ6HM IR7YMWDJ5Y '));
  assert.notEqual(id, fleetKeyId('wf-byntydr27z7j3zsdpih3uulqhi'));
  assert.ok(!key.includes(id));
});
