import test from 'node:test';
import assert from 'node:assert/strict';
import { redactSensitiveText } from '../src/redact.ts';

// Parity fixtures: expected outputs generated by running the daemon's Go
// redactSensitiveText (internal/acp/types.go) on the same inputs. The renderer
// paints optimistic rows with this function while the daemon redacts the
// persisted copy at ingestion — any byte of divergence re-creates the
// "text changes on reload" bug, so these must stay byte-identical.
const GO_PARITY: Array<[input: string, output: string]> = [
  ['receipt says token: abc123 and password=hunter2 ok', 'receipt says token:[redacted] and password=[redacted] ok'],
  ['Authorization: Bearer sk-live-abcDEF123 rest', 'Authorization: Bearer [redacted] rest'],
  ['api_key="quoted value" done', 'api_key=[redacted] done'],
  ["GITHUB_TOKEN=ghp_x1 secret: 's3'", 'GITHUB_TOKEN=[redacted] secret:[redacted]'],
  ['tokens: 85 y max_tokens=4096', 'tokens: 85 y max_tokens=4096'],
  ['el credential : espacios', 'el credential :[redacted]'],
  ['Bearer  doblespacio', 'Bearer [redacted]'],
  ['no secrets aqui', 'no secrets aqui'],
  ['password=', 'password='],
  ['token:[redacted]', 'token:[redacted]'],
];

test('renderer redaction is byte-identical to the daemon redactor', () => {
  for (const [input, output] of GO_PARITY) {
    assert.equal(redactSensitiveText(input), output, `input: ${input}`);
  }
});

test('redaction is idempotent so re-persisted rows never drift further', () => {
  for (const [input] of GO_PARITY) {
    const once = redactSensitiveText(input);
    assert.equal(redactSensitiveText(once), once, `input: ${input}`);
  }
});
