// The client half of fleet enrolment (remote-plan D3 / E2).
//
// One key defines "my machines". A client that holds it proves so without ever
// sending it, and then derives — rather than receives — the device token that
// grants it access. Nothing reusable crosses the wire in either direction,
// which is what makes this safe to run before TLS exists.
//
// The daemon side is `internal/fleet/fleet.go`; the two must agree byte for
// byte, so `tests/fleet-derivation.test.ts` checks this file against vectors
// generated by that one. Traps that cost real time and are pinned by tests:
//
//   · Go writes base32 UNPADDED. Most decoders reject that, so pad first.
//   · Every field in the HMAC input gets a trailing NUL, including the last.
//   · The approval EVENT arrives before the enrol REPLY on the same socket.
//     That is the transport's problem, not this file's, but it is where the
//     time goes if a client assumes reply-first.

import { hmacSha256, sha256, toHex, utf8 } from './sha256.ts';

export const KEY_PREFIX = 'wf-';
export const PROOF_CONTEXT = 'workass-fleet-proof-v1';
export const TOKEN_CONTEXT = 'workass-fleet-token-v1';
const SECRET_BYTES = 16;
const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

export class FleetKeyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'FleetKeyError';
  }
}

/**
 * Accept what a human actually types — any case, with spaces, dashes or
 * underscores anywhere, with or without the prefix — and return the canonical
 * form. A key is read off one screen and typed into another; being strict about
 * whitespace only ever punishes the person doing the typing.
 */
export function normalizeFleetKey(input: string): string {
  const cleaned = String(input ?? '').trim().toLowerCase().replace(/[\s\-_]/g, '');
  const body = cleaned.startsWith('wf') ? cleaned.slice(2) : cleaned;
  if (!body) throw new FleetKeyError('that is not a fleet key: it is empty');
  const raw = decodeBase32(body);
  if (raw.length !== SECRET_BYTES) throw new FleetKeyError('that is not a fleet key: wrong length');
  return KEY_PREFIX + body;
}

/** RFC 4648 base32, padding optional — Go emits none. */
export function decodeBase32(input: string): Uint8Array {
  const text = String(input ?? '').toUpperCase().replace(/=+$/, '');
  const out: number[] = [];
  let buffer = 0;
  let bits = 0;
  for (const char of text) {
    const value = BASE32_ALPHABET.indexOf(char);
    if (value < 0) throw new FleetKeyError('that is not a fleet key: unreadable characters');
    buffer = (buffer << 5) | value;
    bits += 5;
    if (bits >= 8) {
      bits -= 8;
      out.push((buffer >> bits) & 0xff);
    }
  }
  return new Uint8Array(out);
}

/**
 * The shared derivation. Mirrors `derive()` in fleet.go: each part is written
 * followed by a NUL separator, so moving a character across a field boundary
 * cannot produce the same input from different fields.
 */
function derive(key: string, context: string, serverNonce: string, clientNonce: string, machineId: string): string {
  const secret = decodeBase32(normalizeFleetKey(key).slice(KEY_PREFIX.length));
  const parts = [context, serverNonce, clientNonce, machineId];
  const encoded = parts.map((part) => utf8(part ?? ''));
  const total = encoded.reduce((sum, part) => sum + part.length + 1, 0);
  const message = new Uint8Array(total);
  let offset = 0;
  for (const part of encoded) {
    message.set(part, offset);
    offset += part.length;
    message[offset] = 0;
    offset += 1;
  }
  return toHex(hmacSha256(secret, message));
}

/** What the client sends to show it holds the key without revealing it. */
export function fleetProof(key: string, serverNonce: string, clientNonce: string, machineId: string): string {
  return derive(key, PROOF_CONTEXT, serverNonce, clientNonce, machineId);
}

/**
 * The device token, computed rather than received. The daemon derives the same
 * value from the same inputs and stores only its hash, so this never travels.
 */
export function fleetDeviceToken(key: string, serverNonce: string, clientNonce: string, machineId: string): string {
  return derive(key, TOKEN_CONTEXT, serverNonce, clientNonce, machineId);
}

/** The client's contribution to the exchange. 16 bytes, hex. */
export function newClientNonce(random: (bytes: number) => Uint8Array = defaultRandom): string {
  return toHex(random(16));
}

function defaultRandom(bytes: number): Uint8Array {
  const out = new Uint8Array(bytes);
  const source = (globalThis as { crypto?: { getRandomValues?: (a: Uint8Array) => Uint8Array } }).crypto;
  if (source?.getRandomValues) return source.getRandomValues(out);
  // `crypto.getRandomValues` is available in every browser regardless of secure
  // context — unlike crypto.subtle. This branch exists only so the module is
  // importable in a bare test runner; a caller with no CSPRNG passes its own.
  throw new FleetKeyError('no secure random source; pass one explicitly');
}

/** The challenge document `fleet:challenge` returns. */
export interface FleetChallenge {
  enabled: boolean;
  machineId: string;
  serverNonce?: string;
  keyIds?: string[];
  nonceTtlMs?: number;
}

export interface FleetEnrolment {
  clientNonce: string;
  proof: string;
  /** Derive it now, persist it only once the daemon says ok. */
  deviceToken: string;
}

/**
 * Everything a client computes between receiving a challenge and sending
 * `fleet:enroll`. Kept separate from the transport so it is testable without a
 * socket, and so the same function serves the browser and any other client.
 */
export function answerFleetChallenge(
  key: string,
  challenge: FleetChallenge,
  random?: (bytes: number) => Uint8Array,
): FleetEnrolment {
  if (!challenge?.enabled) throw new FleetKeyError('that machine has no fleet key yet');
  const serverNonce = String(challenge.serverNonce ?? '');
  const machineId = String(challenge.machineId ?? '');
  if (!serverNonce || !machineId) throw new FleetKeyError('challenge is missing its nonce or machine id');
  const clientNonce = newClientNonce(random);
  return {
    clientNonce,
    proof: fleetProof(key, serverNonce, clientNonce, machineId),
    deviceToken: fleetDeviceToken(key, serverNonce, clientNonce, machineId),
  };
}

/**
 * Whether a machine advertising these fleet ids would accept this key. The ids
 * are one-way hashes, published in the health card and the beacon precisely so
 * a client can answer this without asking a human again.
 *
 * The id is sha256(keyIdContext ‖ 0x00 ‖ canonicalKey), first 8 bytes, hex —
 * `KeyIDOf` in fleet.go.
 */
export function fleetKeyId(key: string): string {
  const message = utf8('workass-fleet-keyid-v1\u0000' + normalizeFleetKey(key));
  return toHex(sha256(message)).slice(0, 16);
}
