package main

import (
	"crypto/sha256"
	"fmt"
	"strings"
	"time"

	"workass/internal/acp"
	"workass/internal/chat"
	providercontract "workass/internal/provider"
)

// deliverSubagentCompletion crosses the manager/actor boundary only after the
// bounded terminal receipt is durable. The actor operation id is derived from
// that receipt, so restart recovery can safely retry the same admission.
func (r *providerChatRuntime) deliverSubagentCompletion(tabID, chatID string, receipt acp.SubagentReceipt) error {
	if r == nil || r.manager == nil || strings.TrimSpace(receipt.ReceiptID) == "" {
		return fmt.Errorf("tracked subagent completion is unavailable")
	}
	actor, err := r.actor(chatID)
	if err != nil {
		return err
	}
	state := actor.engine.Snapshot()
	if state.Deleted || state.Presentation.TabID != strings.TrimSpace(tabID) {
		// A deleted or re-homed actor must never be recreated or addressed through
		// another tab. Returning success acknowledges this permanently ineligible
		// owner and prevents restart recovery from resurrecting it.
		return nil
	}
	if receipt.Status != "done" && receipt.Status != "failed" {
		return nil
	}
	operationID := subagentCompletionOperationID(tabID, chatID, receipt.ReceiptID)
	message := formatSubagentCompletion(receipt)
	laneID := providercontract.LaneID(strings.TrimSpace(receipt.OriginLaneID))
	actor.mu.Lock()
	state = actor.engine.Snapshot()
	if state.Deleted || state.Presentation.TabID != strings.TrimSpace(tabID) {
		actor.mu.Unlock()
		return nil
	}
	if _, exists := state.Operations[operationID]; exists {
		if actorHasSubagentCompletion(state, operationID, laneID, message) {
			actor.mu.Unlock()
			return nil
		}
		actor.mu.Unlock()
		return fmt.Errorf("tracked subagent receipt operation conflicts with existing chat input")
	}
	if laneID == "" {
		laneID = state.DesiredLaneID
	}
	lane, ok := state.Lanes[laneID]
	if !ok || lane.Identity.ChatID != strings.TrimSpace(chatID) {
		actor.mu.Unlock()
		return fmt.Errorf("originating provider lane is unavailable for tracked subagent completion")
	}
	presentation := providercontract.TurnPresentation{
		UserMessageID:      stableAgentMessageIdentity("u", operationID),
		AssistantMessageID: stableAgentMessageIdentity("a", operationID),
		QueueID:            string(operationID), PromptText: message, Title: state.Presentation.Title,
		Origin: "agent", StartedAt: time.Now().UTC().Format(time.RFC3339Nano),
	}
	if err := actor.engine.Apply(chat.Submit{
		OperationID: operationID, LaneID: laneID, Text: message, ModelID: lane.ModelID, ModeID: lane.ModeID,
		Presentation: presentation,
	}); err != nil {
		actor.mu.Unlock()
		return err
	}
	actor.mu.Unlock()
	actor.coordinator.Wake()
	return nil
}

func actorHasSubagentCompletion(state chat.State, operationID providercontract.OperationID, laneID providercontract.LaneID, message string) bool {
	match := func(input chat.QueueEntry) bool {
		laneMatches := laneID == "" || input.LaneID == laneID
		return input.OperationID == operationID && laneMatches && input.Text == message && input.Presentation.Origin == "agent"
	}
	if state.Foreground != nil && match(state.Foreground.Input) {
		return true
	}
	for _, input := range state.Queue {
		if match(input) {
			return true
		}
	}
	for _, event := range state.Ledger {
		laneMatches := laneID == "" || event.LaneID == laneID
		if event.OperationID == operationID && laneMatches && event.Role == "user" && event.Text == message {
			return true
		}
	}
	return false
}

func subagentCompletionOperationID(tabID, chatID, receiptID string) providercontract.OperationID {
	sum := sha256.Sum256([]byte(strings.Join([]string{
		"tracked-subagent-completion-v1", strings.TrimSpace(tabID), strings.TrimSpace(chatID), strings.TrimSpace(receiptID),
	}, "\x00")))
	return providercontract.OperationID(fmt.Sprintf("subagent-completion:%x", sum[:16]))
}

func formatSubagentCompletion(receipt acp.SubagentReceipt) string {
	var b strings.Builder
	b.WriteString("Internal agent completion notice. A tracked subagent finished; this notice was generated by Workass and is not a human message.\n")
	fmt.Fprintf(&b, "Receipt: %s\nAgent: %s\nOutcome: %s\n", receipt.ReceiptID, receipt.Label, receipt.Status)
	if receipt.Status == "failed" {
		b.WriteString("Failure:\n")
		b.WriteString(receipt.Error)
	} else {
		b.WriteString("Result:\n")
		b.WriteString(receipt.Result)
	}
	return redactedSessionString(b.String())
}
